services:
  app:
    # my pc
    # build:
    #   ./bot/

    # server
    image: ubilby/task_tracker:latest
    env_file: .env  # Подключаем .env файл для app
    command: ["python", "main.py"]
    depends_on:
      - db
    environment:
      - DB_HOST=db
      - DB_PORT=5432
      - DB_NAME=${POSTGRES_DB}
      - DB_USER=${POSTGRES_USER}
      - DB_PASSWORD=${POSTGRES_PASSWORD}

  db:
    image: postgres:latest
    env_file: .env  # Подключаем .env файл для db
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    ports:
      - "5432:5432"

volumes:
  postgres_data: