services:
  app:
    # local
    build:
      ./bot/
    # server
    # image: ubilby/task_tracker:latest

    # local
    # env_file: ./bot/.env  # Подключаем .env файл для app
    # server
    env_file: .env

    command: ["python", "main.py"]
    depends_on:
      - db
    environment:
      - DB_HOST=db
      - DB_PORT=5432
      - DB_NAME=${POSTGRES_DB}
      - DB_USER=${POSTGRES_USER}
      - DB_PASSWORD=${POSTGRES_PASSWORD}

  db:
    image: postgres:latest

    # local
    # env_file: /Users/ubilby/code/python/pets/task-tracker/bot/.env  # Подключаем .env файл для db
    # server
    env_file: .env  # Подключаем .env файл для db

    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    ports:
      - "5432:5432"

volumes:
  postgres_data: